_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 105
            "2":
                - 1
                - 5
                - 53
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
batch_size:
    value: 64
clip_grad_norm:
    value: 1
conditional:
    value: false
device:
    value: cpu
energy:
    value: gmm
epochs:
    value: 2000
eval_interval:
    value: 100
guidance_scale:
    value: 2.5
hidden_dim:
    value: 128
latent_dim:
    value: 2
log_interval:
    value: 1
loss_type:
    value: tb_avg
lr_policy:
    value: 0.0001
num_conditions:
    value: 4
num_layers:
    value: 3
num_timesteps:
    value: 1000
offline:
    value: false
output_dir:
    value: results/ablation_studies/energy_ablation/gmm
project_name:
    value: gfn-diffusion-experiments
run_name:
    value: ablation_energy_gmm
save_interval:
    value: 100
schedule_type:
    value: linear
seed:
    value: 42
use_scheduler:
    value: false
vae_path:
    value: null
vae_type:
    value: mnist
wandb:
    value: true
wandb_entity:
    value: null
wandb_project:
    value: gfn-diffusion-experiments
